# Language Modelling using RNN 

# i) Probability Prediction

## Importing necessary libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

from keras.models import Sequential
from keras.layers import SimpleRNN, Dense, Embedding

from keras.utils import to_categorical


## Preprocessing Data

In [ ]:
data = """ Jack and Jill went up the hill .\n To fetch a pail of water .\n Jack fell down and broke his crown .\n And Jill came tumbling after . """
print(data)

 Jack and Jill went up the hill .
 To fetch a pail of water .
 Jack fell down and broke his crown .
 And Jill came tumbling after . 


In [ ]:
data_splitted = data.split('\n')
data_splitted

[' Jack and Jill went up the hill .',
 ' To fetch a pail of water .',
 ' Jack fell down and broke his crown .',
 ' And Jill came tumbling after . ']

Adding filters except '.' as we dont want '.' to be filtered out by the tokenizer but be considered as a token

In [ ]:
tokenizer = Tokenizer(filters='!"#$%&()*+,-/:;<=>?@[\\]^_`{|}~')

# Initializing vocabulary
tokenizer.fit_on_texts(data_splitted)
print(tokenizer.word_index)

vocab_length = len(tokenizer.word_index) + 1
vocab_length

{'.': 1, 'and': 2, 'jack': 3, 'jill': 4, 'went': 5, 'up': 6, 'the': 7, 'hill': 8, 'to': 9, 'fetch': 10, 'a': 11, 'pail': 12, 'of': 13, 'water': 14, 'fell': 15, 'down': 16, 'broke': 17, 'his': 18, 'crown': 19, 'came': 20, 'tumbling': 21, 'after': 22}


23

**Converting text to numerical sequences based on word index**

In [ ]:
sequences = tokenizer.texts_to_sequences(data_splitted)
sequences

[[3, 2, 4, 5, 6, 7, 8, 1],
 [9, 10, 11, 12, 13, 14, 1],
 [3, 15, 16, 2, 17, 18, 19, 1],
 [2, 4, 20, 21, 22, 1]]

**Removing last word index from input as it is not used in the model**

In [ ]:
X = []
y = []

for i in range(len(sequences)):
  X.append(sequences[i][:-1])

y = sequences

print(X)
print(y)

[[3, 2, 4, 5, 6, 7, 8], [9, 10, 11, 12, 13, 14], [3, 15, 16, 2, 17, 18, 19], [2, 4, 20, 21, 22]]
[[3, 2, 4, 5, 6, 7, 8, 1], [9, 10, 11, 12, 13, 14, 1], [3, 15, 16, 2, 17, 18, 19, 1], [2, 4, 20, 21, 22, 1]]


**Adding 0 as x<0> and y<0> for all inputs and outputs**

In [ ]:
for x in X:
  x.insert(0,0)

for op in y:
  op.insert(0,0)

X
y

[[0, 3, 2, 4, 5, 6, 7, 8, 1],
 [0, 9, 10, 11, 12, 13, 14, 1],
 [0, 3, 15, 16, 2, 17, 18, 19, 1],
 [0, 2, 4, 20, 21, 22, 1]]

**Making every input of the same length**

In [ ]:
# finding the max length of input sequences
max_len = 0; 
for x in X:
  max_len = max(max_len,len(x))

max_len

8

**Padding X with 0 to make length of all input same**

In [ ]:
X = pad_sequences(X,max_len,padding='pre')
X

array([[ 0,  3,  2,  4,  5,  6,  7,  8],
       [ 0,  0,  9, 10, 11, 12, 13, 14],
       [ 0,  3, 15, 16,  2, 17, 18, 19],
       [ 0,  0,  0,  2,  4, 20, 21, 22]], dtype=int32)

**Adding 0 to y because of padding in X**

In [ ]:
y = pad_sequences(y,max_len,padding='pre')
y

array([[ 3,  2,  4,  5,  6,  7,  8,  1],
       [ 0,  9, 10, 11, 12, 13, 14,  1],
       [ 3, 15, 16,  2, 17, 18, 19,  1],
       [ 0,  0,  2,  4, 20, 21, 22,  1]], dtype=int32)

**Converting to One-Hot Encoding**

In [ ]:
y = to_categorical(y,num_classes = vocab_length)
y

array([[[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],

In [ ]:
y.shape

(4, 8, 23)

## Building the Model

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=vocab_length, output_dim=10))
model.add(SimpleRNN(50,return_sequences=True))
model.add(Dense(units=vocab_length, activation='softmax'))

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, None, 10)          230       
_________________________________________________________________
simple_rnn_4 (SimpleRNN)     (None, None, 50)          3050      
_________________________________________________________________
dense_4 (Dense)              (None, None, 23)          1173      
Total params: 4,453
Trainable params: 4,453
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(X,y,epochs=200)

Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 3.1384 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 8ms/step - loss: 3.1055 - accuracy: 0.0938
Epoch 3/200
1/1 [==============================] - 0s 8ms/step - loss: 3.0775 - accuracy: 0.1562
Epoch 4/200
1/1 [==============================] - 0s 7ms/step - loss: 3.0463 - accuracy: 0.2188
Epoch 5/200
1/1 [==============================] - 0s 8ms/step - loss: 3.0096 - accuracy: 0.1875
Epoch 6/200
1/1 [==============================] - 0s 8ms/step - loss: 2.9669 - accuracy: 0.1875
Epoch 7/200
1/1 [==============================] - 0s 8ms/step - loss: 2.9190 - accuracy: 0.1875
Epoch 8/200
1/1 [==============================] - 0s 8ms/step - loss: 2.8678 - accuracy: 0.1875
Epoch 9/200
1/1 [==============================] - 0s 6ms/step - loss: 2.8154 - accuracy: 0.1875
Epoch 10/200
1/1 [==============================] - 0s 8ms/step - loss: 2.7631 - accuracy: 0.2188
Epoch 11/200
1/1 [========

## Function for predicting probability of a Sentence

In [ ]:
def prob_of_sentence(model,tokenizer,sentence):

  # converting sentence into numerical form
  encoded_sentence = tokenizer.texts_to_sequences([sentence])[0]
  print(encoded_sentence)

  # adding 0 as X<0>
  encoded_sentence.insert(0,0)
  print(encoded_sentence)

  encoded_sentence = np.array(encoded_sentence).reshape((1,-1))
  print(encoded_sentence)

  prob = model.predict_proba(encoded_sentence)
  print(prob.shape)

  probability = 1
  for i in range(0,prob.shape[1] - 1):
    probability *= prob[0,i,encoded_sentence[0,i+1]]
  print(probability)

In [ ]:
prob_of_sentence(model,tokenizer,"Jack and Jill .")

[3, 2, 4, 1]
[0, 3, 2, 4, 1]
[[0 3 2 4 1]]
(1, 5, 23)
1.8183255523435641e-06


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


## ii) Sentence Generation

## Random sentence generation without seed

In [ ]:
class color:
   PURPLE = '\033[95m'
   CYAN = '\033[96m'
   DARKCYAN = '\033[36m'
   BLUE = '\033[94m'
   GREEN = '\033[92m'
   YELLOW = '\033[93m'
   RED = '\033[91m'
   BOLD = '\033[1m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'

In [ ]:
def sample_all_wo_seed(model,tokenizer,n_words,vocab_length):
  encoded_sentence = []
  inp_text = ''

  for i in range(n_words):
    print('-'*50)
    print('Input text : ', inp_text)

    # converting sentence into numerical form
    encoded_sentence = tokenizer.texts_to_sequences([inp_text])[0]

    # adding 0 as X<0>
    encoded_sentence.insert(0,0)
    
    encoded_sentence = np.array(encoded_sentence).reshape((1,-1))
    print("For i : {} Encoded is : {}".format(i, encoded_sentence))

    if i == 0:
      prob = model.predict_proba(encoded_sentence, verbose= 0)
      y_hat = 0
      while y_hat == 0:
        y_hat = np.random.choice(range(vocab_length),p=prob.ravel())
        y_hat = np.array(y_hat).reshape((1,-1))
      print("For i : {} yhat in if is : {}".format(i, y_hat))

    else:
      prob = model.predict_proba(encoded_sentence, verbose= 0)
      print(prob.shape)
      y_hat = np.append(y_hat,0)
      y_hat = np.array(y_hat).reshape((1,-1))

      while y_hat[0][i] == 0:
        y_hat[0][i] = np.random.choice(range(vocab_length),p=prob[0][i].ravel())
      print("For i : {} yhat in else is : {}".format(i, y_hat))

    output_word = ""
    for word, index in tokenizer.word_index.items():
      if index == y_hat[0][i]:
        output_word = word
        break
    inp_text += output_word + ' '

    print('-'*50)

  return inp_text

In [ ]:
print('\n\n' + color.BOLD + sample_all_wo_seed(model,tokenizer,3,vocab_length) + color.END)

--------------------------------------------------
Input text :  
For i : 0 Encoded is : [[0]]
For i : 0 yhat in if is : [[3]]
--------------------------------------------------
--------------------------------------------------
Input text :  jack 
For i : 1 Encoded is : [[0 3]]
(1, 2, 23)
For i : 1 yhat in else is : [[3 2]]
--------------------------------------------------
--------------------------------------------------
Input text :  jack and 
For i : 2 Encoded is : [[0 3 2]]
(1, 3, 23)
For i : 2 yhat in else is : [[ 3  2 16]]
--------------------------------------------------


jack and down 


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


## Sentence generation with highest probability

In [ ]:
def sample_all_wo_seed_with_hp(model,tokenizer,n_words,vocab_length):
  encoded_sentence = []
  inp_text = ''

  for i in range(n_words):
    print('-'*50)
    print('Input text : ', inp_text)

    # converting sentence into numerical form
    encoded_sentence = tokenizer.texts_to_sequences([inp_text])[0]

    # adding 0 as X<0>
    encoded_sentence.insert(0,0)
    
    encoded_sentence = np.array(encoded_sentence).reshape((1,-1))
    print("For i : {} Encoded is : {}".format(i, encoded_sentence))

    if i == 0:
      prob = model.predict_proba(encoded_sentence, verbose= 0)
      y_hat = 0
      while y_hat == 0:
        y_hat = np.random.choice(range(vocab_length),p=prob.ravel())
        y_hat = np.array(y_hat).reshape((1,-1))
      print("For i : {} yhat in if is : {}".format(i, y_hat))

    else:
      prob = model.predict_proba(encoded_sentence, verbose= 0)
      print(prob.shape)
      y_hat = np.append(y_hat,0)
      y_hat = np.array(y_hat).reshape((1,-1))

      # while y_hat[0][i] == 0:
      
      y_hat[0][i] = np.argmax(prob[0][i].ravel()[1:] , axis=0)
      print("For i : {} yhat in else is : {}".format(i, y_hat))

    output_word = ""
    for word, index in tokenizer.word_index.items():
      if index == y_hat[0][i]:
        output_word = word
        break
    inp_text += output_word + ' '

    print('-'*50)

  return inp_text

In [ ]:
print('\n\n' + color.BOLD + sample_all_wo_seed_with_hp(model,tokenizer,5,vocab_length) + color.END)

--------------------------------------------------
Input text :  
For i : 0 Encoded is : [[0]]
For i : 0 yhat in if is : [[3]]
--------------------------------------------------
--------------------------------------------------
Input text :  jack 
For i : 1 Encoded is : [[0 3]]
(1, 2, 23)
For i : 1 yhat in else is : [[ 3 14]]
--------------------------------------------------
--------------------------------------------------
Input text :  jack water 
For i : 2 Encoded is : [[ 0  3 14]]
(1, 3, 23)
For i : 2 yhat in else is : [[ 3 14  3]]
--------------------------------------------------
--------------------------------------------------
Input text :  jack water jack 
For i : 3 Encoded is : [[ 0  3 14  3]]


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


(1, 4, 23)
For i : 3 yhat in else is : [[ 3 14  3  4]]
--------------------------------------------------
--------------------------------------------------
Input text :  jack water jack jill 
For i : 4 Encoded is : [[ 0  3 14  3  4]]
(1, 5, 23)
For i : 4 yhat in else is : [[ 3 14  3  4  5]]
--------------------------------------------------


jack water jack jill went 
